### ISSUE TITLE
配置中心连不上时，client如何感知呢？谢谢

### ISSUE THREAD

**Issue by yiippee** [apolloconfig/agollo#171]
如题。
好像没有将出错信息抛给上层业务，而是默认使用备份的配置。那业务层如何感知配置中心连不上呢？
谢谢。

**Comment by zouyx** [comment]
> 如题。
> 好像没有将出错信息抛给上层业务，而是默认使用备份的配置。那业务层如何感知配置中心连不上呢？
> 谢谢。

现在没有插件功能让上层业务系统进行感知，但有打 log，可以基于 error 进行告警。

https://github.com/zouyx/agollo/blob/08e15f2e0ce0db8fd5399c9757f354ec23c74a1d/protocol/http/request.go#L162

**Comment by zouyx** [comment]
如果没有问题，我先关掉
