### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by morysky** [apolloconfig/agollo#174]
**请简单描述bug的场景**
修改后无法实时同步，引起线上故障

**如何重现**
修改配置发布即可

再现行为的步骤：

1.跳到“…”

2.点击“…”

3.向下滚动到“…”

4.见错误

**期望**
请描述期望发生什么

**截图**
如有

**Agollo 版本 :**
 - 4.0.7

**日志信息**

**其他上下文**
如有

**Comment by zouyx** [comment]
请问是否有什么报错信息之类？

**Comment by morysky** [comment]
没有啥报错就是不同步..回退到0.4.7恢复了.

**Comment by zouyx** [comment]
是 v4.0.7  还是 v0.4.7？我好像没找到 v0.4.7 这个包，而 v4.0.7  是最新的。。。

**Comment by morysky** [comment]
对，抱歉，说错啦。

**Comment by zouyx** [comment]
> 对，抱歉，说错啦。

我看前面报问题的时候，写的是4.0.7。后面又说回滚到4.0.7就没问题。我想知道的是有问题版本是？😄

**Comment by morysky** [comment]
抱歉，反馈的时候有点着急，没有确认清楚。

线上正常的是：github.com/zouyx/agollo/v4 v4.0.4。v4.0.4
出问题的：升级到最新的，也就是4.0.7，无法实时同步.

**Comment by zouyx** [comment]
> 抱歉，反馈的时候有点着急，没有确认清楚。
> 
> 线上正常的是：github.com/zouyx/agollo/v4 v4.0.4。v4.0.4
> 出问题的：升级到最新的，也就是4.0.7，无法实时同步.

好的，我看看

**Comment by zouyx** [comment]
> 抱歉，反馈的时候有点着急，没有确认清楚。
> 
> 线上正常的是：github.com/zouyx/agollo/v4 v4.0.4。v4.0.4
> 出问题的：升级到最新的，也就是4.0.7，无法实时同步.

@morysky 我模拟了一下，没模拟出来。。。大佬，能否提供一下具体的问题点。。

**Comment by morysky** [comment]
额，大佬你才是真大佬...要不我先关了， 我自己线下debug下。。。

**Comment by zouyx** [comment]
> 额，大佬你才是真大佬...要不我先关了， 我自己线下debug下。。。

其实你可以详细一点告诉我场景，我才好重现。

或者发个邮件到我邮箱，添加一下我私人微信描述一下也可以。
