### ISSUE TITLE
是否有开关可以关掉sync逻辑，仅应用启动的时候加载一次配置

### ISSUE THREAD

**Issue by yldian** [apolloconfig/agollo#178]

**Comment by zouyx** [comment]
我看了一下，暂时好像没有这种玩法，但你可以通过屏蔽代码达到这种效果，代码如下：
https://github.com/apolloconfig/agollo/blob/ee7b414c1365dbc1fc41785138c7f0bf335c6a87/client.go#L121

是否能跟我描述一下，是什么场景需要呢？

**Comment by yldian** [comment]
谢谢！

只是想把配置放在apollo里面，但是没有运行时更改配置/生效的需求。
