### ISSUE TITLE
能指定env吗? 我看默认是DEV环境的，go客户端能指定具体哪个环境吗

### ISSUE THREAD

**Issue by gdut17** [apolloconfig/agollo#184]
**请简单描述bug的场景**

**如何重现**

再现行为的步骤：

1.跳到“…”

2.点击“…”

3.向下滚动到“…”

4.见错误

**期望**
请描述期望发生什么

**截图**
如有

**Agollo 版本 :**

**日志信息**

**其他上下文**
如有

**Comment by zouyx** [comment]
https://www.apolloconfig.com/#/zh/usage/other-language-client-user-guide，apollo 现在没有提供通过环境获取信息的参数。而部署模型推荐是：每一个环境一个实例，通过域名区分。
