### ISSUE TITLE
获取不到原始内容结构

### ISSUE THREAD

**Issue by hhy5861** [apolloconfig/agollo#185]
希望可以提供方法获取原始数据结构。而不是强制转成properties结构。

或者提供结构体解析原始数据。比如，yaml, xml。我记得之前是可以的。GetContent()返回convertToProperties的数据结构。

**Comment by zouyx** [comment]
可以通过转换器处理：https://github.com/zouyx/agollo_demo/blob/f45ac5a489b95b862c9a5571e37082a00860ce67/custom/file/check.go#L23

当然，你也可以不转换
