### ISSUE TITLE
[BUG]字符串列表配置通过GetStringSliceValue获取的是空列表

### ISSUE THREAD

**Issue by gzq0616** [apolloconfig/agollo#186]
**请简单描述bug的场景**
apollo的配置如下：
keytest = ["a", "b", "c"]

**如何重现**
client.GetStringSliceValue("keytest", nil)
获取到的值为空列表[]

再现行为的步骤：
//GetStringSliceValue 获取[]string 配置值
func (c *Client) GetStringSliceValue(key string, defaultValue []string) []string {
	value := c.getConfigValue(key)

	if value == nil {
		return defaultValue
	}
	s, ok := value.([]string)   //  这个地方断言失败
	if !ok {
		return defaultValue
	}
	return s
}

**期望**
能获取到字符串列表

**Agollo 版本 :**
 - Version [v4.0.9]

**Comment by zouyx** [comment]
收到，我今天尝试一下

**Comment by zouyx** [comment]
client.GetStringSliceValue("keytest", nil)

这个方法获取的是 application 的 namespace，你用的 namespace 是 application 吗？

如果不是请使用以下方法：

cache, _ := client.GetConfigCache(name).Get("keytest")

**Comment by wzlove** [comment]
问题:
client.GetStringSliceValue("keytest", []string{"test"})
apollo配置为 keytest -> ["a","b"]

`
if value == nil {
	return defaultValue
}
s, ok := value.([]string)   //  这个地方断言失败
if !ok {
	return defaultValue
}
return s
`
目前解析apollo解析不了字符串类型

**Comment by touch-head-optimistically** [comment]
keytest = ["a", "b", "c"]
这种方式好像并不能被原生的识别为[]string格式，要么就是GetSting读取然后再Split


所以我准备换成这样
a.bb.cc = host1,host2,host3

目前是逗号分隔然后解析
https://github.com/touch-head-optimistically/agollo/pull/1/files

**Comment by touch-head-optimistically** [comment]
@zouyx 还是我的用法错了吗
