### ISSUE TITLE
[FEATURE] 能否指定client与server连接时使用的header？

### ISSUE THREAD

**Issue by Gera-coder** [apolloconfig/agollo#188]
**功能适用的场景？**
因为业务原因，不能通过IP直连server，需要在请求头中指定域名，比如”host:xx“。

**你需要的功能是否有关联问题？**
目前没有找到不改agollo代码来实现该功能的方法。

**你期望的解决方案是？**
可以在配置中指定访问server时使用的host。

**Comment by zenghur** [comment]
这样不成功的，Host不能通过这样来设置，

**Comment by zenghur** [comment]
req.Header.Set("User-Agent", "GolangSpider/1.0")
req.Header.Set("Host", "gltest.com") //incorrect way to set Hostreq.Host = "gltest.com"

**Comment by zenghur** [comment]
```
req.Header.Set("Host", "github.com")  // 这样不能设置成功
req.Host = "github.com"  // 这样可以
```
SetHTTPAuth这个方法不行哦 @zouyx
