### ISSUE TITLE
[BUG]golang环境是否有要求？1.15 不能运行

### ISSUE THREAD

**Issue by richardJiang** [apolloconfig/agollo#191]
github.com/apolloconfig/agollo/v4 imports
        github.com/apolloconfig/agollo/v4/utils/parse/yaml imports
        github.com/spf13/viper imports
        github.com/spf13/afero tested by
        github.com/spf13/afero.test imports
        testing/fstest: package testing/fstest is not in GOROOT (C:\go1158\src\testing\fstest)

使用go mod 管理之后提示这个错误

go version 1.15.8
agollo version v4.0.9

**Comment by richardJiang** [comment]
https://github.com/spf13/viper/issues/1161
same issure

**Comment by zouyx** [comment]
应该是没有要求，但我看是如果 1.15 的话，需要 upgrade 到 1.15.10+

**Comment by richardJiang** [comment]
viper 里面使用的方法已经超前到了1.16了

**Comment by zouyx** [comment]
> viper 里面使用的方法已经超前到了1.16了

那看来只能回滚版本？

**Comment by zouyx** [comment]
> viper 里面使用的方法已经超前到了1.16了

https://github.com/zouyx/agollo_demo/runs/4403694463?check_suite_focus=true

我刚刚用 1.13 试了下，当前4.0.9 也是没问题喔

**Comment by richardJiang** [comment]
我通过升级搞定的，如果现在没有我就关掉吧

**Comment by zouyx** [comment]
我还想了解下，viper 是 agollo 引进来的吗？还是有组件引进来的，go mod graph 看看？

**Comment by richardJiang** [comment]
```
module github.com/apolloconfig/agollo/v4

require (
	github.com/spf13/viper v1.8.1
	github.com/tevid/gohamcrest v1.1.1
)

go 1.13
```

这个是agollo的go mod 可以看到使用的viper是1.8.1

这里面引用了

github.com/spf13/afero v1.6.0
这个

这个里面用到了


```
package afero

import (
	"bytes"
	"errors"
	"io"
	"io/fs"
	"os"
	"testing"
	"testing/fstest"
	"time"
)
```

然而 "testing/fstest" 这个包是go 1.16 才有的。1.15升级根本没用
