### ISSUE TITLE
[BUG] 指定配置备份路径后如果path不存在，不会自动创建出来

### ISSUE THREAD

**Issue by thisXYH** [apolloconfig/agollo#195]
**请简单描述bug的场景**
 指定配置备份路径后如果path不存在，不会自动创建出来

**如何重现**
指定一个不存在的路径保存配置文件，比如  ./conf 
获取配置后，配置文件并没有被保存到本地。

**期望**
期望能自动创建出不存在的路径，并且备份配置文件。

**Comment by zouyx** [comment]
我看了下代码，应该是没有创建的，感谢提醒
