### ISSUE TITLE
可否支持yaml格式的文件

### ISSUE THREAD

**Issue by lujiang618** [apolloconfig/agollo#196]
**功能适用的场景？**
在启动时，生成配置文件目前只有json格式的，是否可以生成yaml格式的

**你需要的功能是否有关联问题？**

**你期望的解决方案是？**
支持多格式的配置文件，如json，yaml， yml。可以指定生成文件的类型

**Comment by zouyx** [comment]
https://github.com/zouyx/agollo_demo/blob/72519027c33e2fe5cef17dafe2107bafbcb1f25c/custom/file/check.go#L23

你想要的可能是这种玩法。这些文件格式对于 apollo 来说都是直接获取 key=content 然后自己转换。所以 agollo 提供默认/自己实现转换的插件。

**Comment by lujiang618** [comment]
好的 谢谢

**Comment by zouyx** [comment]
> 好的 谢谢

还有问题吗？没有可以close
