### ISSUE TITLE
[FEATURE] 有没有mustConnect类似的实现？

### ISSUE THREAD

**Issue by yellowmarlboro** [apolloconfig/agollo#201]
**功能适用的场景？**
网络不好的时候，在用 StartWithConfig -> AddChangeListener 之后，调用GetApolloConfigCache.Range 获取的配置为空

**你需要的功能是否有关联问题？**
简明扼要地描述你需要的功能，当 [...]

**你期望的解决方案是？**
有一个mustConnect 或者其他的解决办法？可以在我首次加载配置的时候确保apollo的配置已经读取到。

```golang

func init(){
	client, err := agollo.StartWithConfig(func() (*agolloConfig.AppConfig, error) {
		return c, nil
	})
	if err != nil {
		log.Error("init apollo error")
	}
	client.AddChangeListener(CustomerCustomChangeListener{})
	m := make(map[string]interface{})
	client.GetApolloConfigCache().Range(
		func(key, value interface{}) bool {
			m[key.(string)] = value
			return true
		},
	)
        // m is empty
}
```

**Comment by zouyx** [comment]
现在没有，但我觉得你可以通过快速实现 LoadConfigFile 实现你这个思想
https://github.com/apolloconfig/agollo/blob/9b7275509e8f74312658cc2f185d17e3b2b1efad/env/file/file_handler.go#L28

因为 LoadConfigFile 是在同步失败之后调用，获取本地备份文件。

但你可能要注意一下，同步失败的意思是：包括启动时同步失败，还有运行期的同步失败，这里需要判断一下。

如何使用可以参考：
https://github.com/zouyx/agollo_demo/tree/master/custom/file

当然如果你可以改一下源码也欢迎提交 pr
