### ISSUE TITLE
不能将所有环境的configServer的地址写入apollo-env.properties，然后通过ENV环境变量读取吗？

### ISSUE THREAD

**Issue by kwen94** [apolloconfig/agollo#203]
**请简单描述bug的场景**

目前看到的demo都是go代码中直接指定某个环境的 configServer的地址，
```
func main() {
	c := &config.AppConfig{
		AppID:   "10001",
		Cluster: "default",
		IP:             "http://apollo-config-dev.test.com",
		NamespaceName:  "application",
		IsBackupConfig: true,
		Secret:         "1378146eab674f2321312321d046010a0dd",
	}
```
不能向java那样指定apollo-env.properties文件，通过系统环境变量来读取指定configServer的地址吗？
类似
```java
dev.meta=http://1.1.1.1:8080
fat.meta=http://apollo.fat.xxx.com
uat.meta=http://apollo.uat.xxx.com
pro.meta=http://apollo.xxx.com
```
还是这块需要自己去实现？

**如何重现**

再现行为的步骤：

1.跳到“…”

2.点击“…”

3.向下滚动到“…”

4.见错误

**期望**
请描述期望发生什么

**截图**
如有

**Agollo 版本 :**

**日志信息**

**其他上下文**
如有

**Comment by yellowmarlboro** [comment]
我理解如果用环境变量指定的话，可以配置 `AGOLLO_CONF` 环境变量
比如`dev`环境: AGOLLO_CONF='.../dev.properties'

dev.properties
```json
{
    "appId": "123",
    "cluster": "dev",
    "namespaceName": "application",
    "ip": "1.1.1.1:8080",
    "backupConfigPath":""
}
```

**Comment by zouyx** [comment]
> **请简单描述bug的场景**
> 
> 目前看到的demo都是go代码中直接指定某个环境的 configServer的地址，
> 
> ```
> func main() {
> 	c := &config.AppConfig{
> 		AppID:   "10001",
> 		Cluster: "default",
> 		IP:             "http://apollo-config-dev.test.com",
> 		NamespaceName:  "application",
> 		IsBackupConfig: true,
> 		Secret:         "1378146eab674f2321312321d046010a0dd",
> 	}
> ```
> 
> 不能向java那样指定apollo-env.properties文件，通过系统环境变量来读取指定configServer的地址吗？ 类似
> 
> ```java
> dev.meta=http://1.1.1.1:8080
> fat.meta=http://apollo.fat.xxx.com
> uat.meta=http://apollo.uat.xxx.com
> pro.meta=http://apollo.xxx.com
> ```
> 
> 还是这块需要自己去实现？
> 
> **如何重现**
> 
> 再现行为的步骤：
> 
> 1.跳到“…”
> 
> 2.点击“…”
> 
> 3.向下滚动到“…”
> 
> 4.见错误
> 
> **期望** 请描述期望发生什么
> 
> **截图** 如有
> 
> **Agollo 版本 :**
> 
> * Version [e.g. 22]
> 
> **日志信息**
> 
> **其他上下文** 如有

从理论上来说，在云场景下，java 和 go 应该是不会是同一个环境。如果从传统 IDC 场景上确实会存在你这个情况。还是我这两种情况都没能描述你这个需求的背景？你可以再描述一下您的背景？

**Comment by kwen94** [comment]
比如在dev环境将go应用编译然后做成Docker镜像，然后会将这个镜像发到dev -> uat -> pro 各环境。

configServer也有三个地址对应dev,uat,pro三个环境。

这个Docker镜像会在这些环境中扭转， 那么我可以在 dev  uat pro 三个集群的这个应用的k8s yml中添加 env=XXX。

Docker镜像是同一个，在不同的环境读取到env是不同的，根据不同的env连接对应的configServer，所以前提是go应用中包含了三个环境的configServer的地址。

**Comment by nobodyiam** [comment]
是否可以把 meta 地址作为环境参数传入？

**Comment by zouyx** [comment]
比较快速的解决方案是：把所有环境的 properties 文件都导入进去，然后根据环境设置 `AGOLLO_CONF` [变量](https://github.com/apolloconfig/agollo/blob/fe025898aca7fab3a3129ca3b434293253efa133/env/app_config.go#L63)。
看看是否能解决你的需求？

例如：
整个 docker 包中有：app-test.properties、app-prod.properties 两个文件
测试环境的变量是：
`
AGOLLO_CONF="app-test.properties"
`

生产环境的变量是：
`
AGOLLO_CONF="app-prod.properties"
`

**Comment by zouyx** [comment]
@kwen94

**Comment by kwen94** [comment]
@zouyx 这样也是可以的！

**Comment by zouyx** [comment]
> @zouyx 这样也是可以的！

这个玩法还可以？：）

**Comment by kwen94** [comment]
我比较懒，如果是我，我希望只用读取环境变量 dev、test、uat或prod就可以了

例如整个 docker 包中有：dev.properties、prod.properties 两个文件
开发环境的变量是：
AGOLLO_CONF="env"

生产环境的变量是：
AGOLLO_CONF="prod"

当然你说的指定文件名效果也是一样的。😄😄😄
