### ISSUE TITLE
[BUG] 自定义解析传入的conent为nil

### ISSUE THREAD

**Issue by fengqi** [apolloconfig/agollo#204]
**请简单描述bug的场景**
通过 extension.AddFormatParser(constant.DEFAULT, &Parser{}) 添加的自定义parse，发现传入的值为空

**如何重现**
按这个demo测试，Parse方法收到的数据为空 

https://github.com/zouyx/agollo_demo/blob/master/custom/file/check.go#L76
```
type Parser struct {}

func (d *Parser) Parse(content interface{}) (map[string]interface{}, error) {
	fmt.Println(content)
	return nil, nil
}
```

看了下，https://github.com/apolloconfig/agollo/blob/master/component/remote/sync.go#L85 这里 `configurations[defaultContentKey]` 是没有值的，我使用的是 properties 格式，configurations只有配置信息，没有conent这个key，那 `m, err := parser.Parse(configurations[defaultContentKey])` 传入的就是nil

**期望**
传入content原始内容

**截图**
![1641294558534](https://user-images.githubusercontent.com/517708/148050476-ed291d84-2a9c-4c8d-92a3-69cdccfba4c8.jpg)

**Agollo 版本 :**
1.9.0
我是使用的 https://github.com/apolloconfig/apollo-build-scripts 部署的测试环境。

**Comment by zouyx** [comment]
是用 1.9 来搞的吗？我好像很久没搞过 1.9 。是否能升级一下 client 的版本？

**Comment by fengqi** [comment]
@zouyx 是1.9，升级是指本项目吗还是？

**Comment by zouyx** [comment]
> @zouyx 是1.9，升级是指本项目吗还是？

升级本项目就行了，应该没有什么需要兼容的吧，改一下使用方式，现在也有很多人在用新版本，其实没啥太大区别。

**Comment by zouyx** [comment]
> > > @zouyx 是1.9，升级是指本项目吗还是？
> > 
> > 
> > 升级本项目就行了，应该没有什么需要兼容的吧，改一下使用方式，现在也有很多人在用新版本，其实没啥太大区别。
> 
> 恩，其他的我评估不了，针对这个issue的问题，感觉没问题。

能升级吗？升级的时候，有没有什么问题？

**Comment by fengqi** [comment]
> constant.DEFAULT, &Parser{}

很久没关注Apollo，最近又捡起来了。。。用的最新版测试也是同样的问题，sync和async一样的逻辑，所以有一样的问题

设计思想是传入原始json内容吗，那是不是把这个sync:.processJSONFiles、async.createApolloConfigWithJSON两个方法的入参b []byte转为string传入就行了
