### ISSUE TITLE
[BUG] 日志封装问题

### ISSUE THREAD

**Issue by snailzed** [apolloconfig/agollo#211]
**请简单描述bug的场景**

日志封装问题
1）https://github.com/apolloconfig/agollo/blob/master/component/log/log.go  

![image](https://user-images.githubusercontent.com/15265910/155148955-656ea093-dbad-4ca8-b441-afab28c92925.png)

应该要给改成这样吧？

![image](https://user-images.githubusercontent.com/15265910/155149119-7ba293a6-680f-4c34-997a-af5f19b2339e.png)

2）调用问题
![image](https://user-images.githubusercontent.com/15265910/155149951-56678ec4-c76c-4492-aa78-ea6a205f4fd3.png)

**如何重现**

再现行为的步骤：

1.跳到“…”

2.点击“…”

3.向下滚动到“…”

4.见错误

**期望**
请描述期望发生什么

**截图**
如有

**Agollo 版本 :**

**日志信息**

**其他上下文**
如有

**Comment by zouyx** [comment]
感谢你的意见，如果有问题，可以提交一下 pr。调用问题中，1.确实应该是少了个 参数，2.至于为什么要打个日志，是因为怕抛出去不打日志。
