### ISSUE TITLE
提问：开发人员local环境的配置如何隔离？

### ISSUE THREAD

**Issue by redochenzhen** [apolloconfig/agollo#213]
不同的开发人员，可能使用localhost的服务（比如本地的数据库），这种情况如何处理？

**Comment by nobodyiam** [comment]
Do you mean by [this](https://github.com/apolloconfig/apollo/issues/1560)?

**Comment by zouyx** [comment]
https://github.com/apolloconfig/agollo/blob/6893d9f0439f05878ad8bb30478d28e99cd4c343/client.go#L125
我觉得可以如此操作：
1.配置 [backupConfigPath](https://github.com/apolloconfig/agollo/blob/6893d9f0439f05878ad8bb30478d28e99cd4c343/env/config/config.go#L49)
将服务器的配置拉下来，并保存到备份文件夹 backup。
```
{
    "appId": "test",
    "cluster": "dev",
    "namespaceName": "application",
    "ip": "localhost:8888",
    "backupConfigPath":"./backup"
}
```

2. 让 agolo 不能同步（将 ip 写错，并设置 [muststart=false](https://github.com/apolloconfig/agollo/blob/6893d9f0439f05878ad8bb30478d28e99cd4c343/client.go#L125)），他会自动去寻找本地文件就是 backup 文件夹，并将其内容读取到客户端中。

3. 现在你可以自由修改 backup 中的内容，其中文件名以 namespace 配置中的 namespace 来命名
