### ISSUE TITLE
[BUG] 平均三分钟出现一次超时（504）

### ISSUE THREAD

**Issue by coderpolo** [apolloconfig/agollo#214]
agollo版本：v4.1.0
现象：每3分钟一次504错误。（Connect Apollo Server Fail,url:%s,StatusCode:%d 504）

似乎不影响实际使用，即使发生超时，远端操作可以也很快同步到本地。
但是我们实际使用的时候，会对error日志做监控，如果错误日志太多的话，容易造成误判

**Comment by coderpolo** [comment]
是因为使用了域名连接的原因吗？

**Comment by nobodyiam** [comment]
Apollo won't return the 504 status code, which seems like an issue in your gateway?

**Comment by coderpolo** [comment]
![image](https://user-images.githubusercontent.com/25792424/156487363-7d65ab7e-d6b3-4e06-85e4-c2de4ffd7a02.png)

感觉是用agollo client使用域名连接会出这个问题。之前有人提到过：https://github.com/apolloconfig/agollo/issues/97，但是解决方案点进去404了。。

**Comment by coderpolo** [comment]
> Apollo won't return the 504 status code, which seems like an issue in your gateway?

感谢解答，重新设置了域名的超时之后，已经解决了

**Comment by zouyx** [comment]
> > Apollo won't return the 504 status code, which seems like an issue in your gateway?
> 
> 感谢解答，重新设置了域名的超时之后，已经解决了

ok，没问题可以 close 一下

**Comment by coderpolo** [comment]
close
