### ISSUE TITLE
[BUG] yaml格式namespace取值报错

### ISSUE THREAD

**Issue by xiiiew** [apolloconfig/agollo#215]
当我使用yaml格式的namespace时，用`GetConfig`方法获取非string类型的配置时，会报panic

config.yml:

![image](https://user-images.githubusercontent.com/35555830/158139756-988e86f2-f754-4d05-93cf-f12d7eaaf3d7.png)

取bool类型 panic:

![image](https://user-images.githubusercontent.com/35555830/158139665-a21d78a7-060c-4bd5-9b39-f081e3c9e7e0.png)

取int类型 panic:

![image](https://user-images.githubusercontent.com/35555830/158140263-6729b65d-ef16-4a67-a07b-1baa6ae61a25.png)

当我使用`GetConfigCache`方法不报错

![image](https://user-images.githubusercontent.com/35555830/158141007-85ee75e1-11e4-4b1d-af3b-7d4ec85c8c26.png)

**Comment by zouyx** [comment]
> 当我使用yaml格式的namespace时，用`GetConfig`方法获取非string类型的配置时，会报panic
> 
> config.yml:
> 
> ![image](https://user-images.githubusercontent.com/35555830/158139756-988e86f2-f754-4d05-93cf-f12d7eaaf3d7.png)
> 
> 取bool类型 panic:
> 
> ![image](https://user-images.githubusercontent.com/35555830/158139665-a21d78a7-060c-4bd5-9b39-f081e3c9e7e0.png)
> 
> 取int类型 panic:
> 
> ![image](https://user-images.githubusercontent.com/35555830/158140263-6729b65d-ef16-4a67-a07b-1baa6ae61a25.png)
> 
> 当我使用`GetConfigCache`方法不报错
> 
> ![image](https://user-images.githubusercontent.com/35555830/158141007-85ee75e1-11e4-4b1d-af3b-7d4ec85c8c26.png)

我试过，确实是有问题，我修复一下，感谢提醒。
