### ISSUE TITLE
Go客户端获取apollo中存在一个数据， value是一个string 当这个值过大的时候 会导致部分apollo上获取不到新的value

### ISSUE THREAD

**Issue by baymax-xhl** [apolloconfig/agollo#223]
Go客户端获取apollo中存在一个数据， value是一个string 当这个值过大的时候 会导致部分apollo上获取不到新的value

**Comment by zouyx** [comment]
> Go客户端获取apollo中存在一个数据， value是一个string 当这个值过大的时候 会导致部分apollo上获取不到新的value

是否有个 demo 给我尝试一下？

@baymax-xhl
