### ISSUE TITLE
[BUG] 不同环境下的同名集群共用了一份配置

### ISSUE THREAD

**Issue by fananchong** [apolloconfig/agollo#225]
如图：
![image](https://user-images.githubusercontent.com/20277955/164406667-0b784daf-d54e-45d9-a185-0a8d3ad67b24.png)
我改了 北美-Test 的配置，并发布；新加坡-Test 大陆-Test 配置也变了

**Comment by fananchong** [comment]
![image](https://user-images.githubusercontent.com/20277955/164406976-bee3f835-9d44-417c-b450-f46dff426d44.png)

**Comment by fananchong** [comment]
好像知道原因了，是不是不同环境，部署自己的 meta config db 。这样，环境间配置就不会受到影响了？

**Comment by Anilople** [comment]
> 好像知道原因了，是不是不同环境，部署自己的 meta config db 。这样，环境间配置就不会受到影响了？

see https://www.apolloconfig.com/#/zh/deployment/deployment-architecture
