### ISSUE TITLE
环境的配置是通过secret区分的吗？怎么在连接Apollo的时候指定环境

### ISSUE THREAD

**Issue by chowyu12** [apolloconfig/agollo#228]
type AppConfig struct {
	AppID                   string `json:"appId"`
	Cluster                 string `json:"cluster"`
	NamespaceName           string `json:"namespaceName"`
	IP                      string `json:"ip"`
	IsBackupConfig          bool   `default:"true" json:"isBackupConfig"`
	BackupConfigPath        string `json:"backupConfigPath"`
	Secret                  string `json:"secret"`
	SyncServerTimeout       int    `json:"syncServerTimeout"`
	notificationsMap        *notificationsMap
	currentConnApolloConfig *CurrentApolloConfig
}

**Comment by zouyx** [comment]
如果是服务器不一样通过 ip，如果是配置界面中的[环境](https://www.apolloconfig.com/#/zh/design/apollo-introduction?id=_421-%e6%96%b0%e5%bb%bacluster)不一样使用其中的 cluster name
