### ISSUE TITLE
apollo客户端连接服务端时未做服务端证书校验，存在服务端仿冒的风险

### ISSUE THREAD

**Issue by zhongxp1219** [apolloconfig/agollo#233]
**请简单描述bug的场景**
apollo客户端连接服务端时未做服务端证书校验，存在服务端仿冒的风险，看如下代码：
![image](https://user-images.githubusercontent.com/22350886/172378133-5c687f44-653f-4c18-97f7-00a998c32a76.png)

**如何重现**
必现

**期望**
期望客户端具备服务端证书校验的能力，并能够控制是否开启校验

**截图**
![image](https://user-images.githubusercontent.com/22350886/172378368-652c59b7-9ef1-4b49-921d-9c3e51f4cb9f.png)

**Comment by nobodyiam** [comment]
I'm curious about what the actual scenario would be...

**Comment by zouyx** [comment]
> **请简单描述bug的场景** apollo客户端连接服务端时未做服务端证书校验，存在服务端仿冒的风险，看如下代码： ![image](https://user-images.githubusercontent.com/22350886/172378133-5c687f44-653f-4c18-97f7-00a998c32a76.png)
> 
> **如何重现** 必现
> 
> **期望** 期望客户端具备服务端证书校验的能力，并能够控制是否开启校验
> 
> **截图** ![image](https://user-images.githubusercontent.com/22350886/172378368-652c59b7-9ef1-4b49-921d-9c3e51f4cb9f.png)

你好，我想了解下是实际的什么使用场景导致这个问题？还是只是看到代码，觉得有这个问题？
