### ISSUE TITLE
apollo启动的时候必须把所有要用的namespace配置上吗？

### ISSUE THREAD

**Issue by chowyu12** [apolloconfig/agollo#234]
**请简单描述bug的场景**
代码
```
c := &config.AppConfig{
		AppID:          "appid",
		Cluster:        "dev",
		IP:             "http://xxxxxxx:8080",
		NamespaceName:  "application",
		IsBackupConfig: true,
		Secret:         "xxxxxx",
	}
	client, _ := agollo.StartWithConfig(func() (*config.AppConfig, error) {
		return c, nil
	})
	fmt.Println("初始化Apollo配置成功")
       // 获取不到namespace为common 的配置,cache ==nil
        cache := client.GetConfigCache("common")

```

**Comment by richardJiang** [comment]
`//GetConfigAndInit 根据namespace获取apollo配置
func (c *Client) GetConfigAndInit(namespace string) *storage.Config {
	if namespace == "" {
		return nil
	}

	config := c.cache.GetConfig(namespace)

	if config == nil {
		//init cache
		storage.CreateNamespaceConfig(namespace)

		//sync config
		syncApolloConfig.SyncWithNamespace(namespace, c.getAppConfig)
	}

	config = c.cache.GetConfig(namespace)

	return config
}`
syncApolloConfig.SyncWithNamespace(namespace, c.getAppConfig) 这个方法的response没有接，所以并没有拿到对应的配置

**Comment by richardJiang** [comment]
> > **请简单描述bug的场景** 代码
> > ```
> > c := &config.AppConfig{
> > 		AppID:          "appid",
> > 		Cluster:        "dev",
> > 		IP:             "http://xxxxxxx:8080",
> > 		NamespaceName:  "application",
> > 		IsBackupConfig: true,
> > 		Secret:         "xxxxxx",
> > 	}
> > 	client, _ := agollo.StartWithConfig(func() (*config.AppConfig, error) {
> > 		return c, nil
> > 	})
> > 	fmt.Println("初始化Apollo配置成功")
> >        // 获取不到namespace为common 的配置,cache ==nil
> >         cache := client.GetConfigCache("common")
> > ```
> 
> 不一定需要，可以通过 client.GetConfigAndInit() 获取。
