### ISSUE TITLE
[FEATURE] 不建立长连接，无需刷新配置，直接获取配置信息

### ISSUE THREAD

**Issue by wongoo** [apolloconfig/agollo#236]
**功能适用的场景？**
该功能适用于函数计算只需获取一次配置的场景

**你需要的功能是否有关联问题？**
函数计算环境，只需启动的时候获取一次配置。

**你期望的解决方案是？**
我期望改造后，实现：
- 客户端无需建立长连接，无需启动goroutine监听配置刷新

**Comment by zouyx** [comment]
> 

如果想自己实现，代码到这里应该就是返回的数据，但是没有经过格式化。
https://github.com/apolloconfig/agollo/blob/559999e53619fc5e6371345a553970bb0aa16f0a/client.go#L122

是需要放回 client 里面，从 client 方法获取对应值？
