### ISSUE TITLE
[BUG] AppConfig里面的Label，似乎不生效

### ISSUE THREAD

**Issue by garyfu9527** [apolloconfig/agollo#237]
**请简单描述bug的场景**
我想测试灰度参加，在Apollo里面设置了灰度Label，并把Label填入AppConfig中，但这地方返回的结果，似乎不太确定，有时候读取不到灰度的值，有时候又一直返回灰度的值。

**如何重现**

再现行为的步骤：

1.跳到“…”

2.点击“…”

3.向下滚动到“…”

4.见错误

**期望**
请描述期望发生什么

**截图**
如有

**Agollo 版本 :**

**日志信息**

**其他上下文**
如有

**Comment by nobodyiam** [comment]
Would you please provide a detailed duplication scenario?
