### ISSUE TITLE
请问支持yaml配置格式的读取吗？

### ISSUE THREAD

**Issue by MadlifeZhou** [apolloconfig/agollo#238]
注意到只支持.properties的读取，请问是否支持yaml格式的读取呢？

**Comment by zouyx** [comment]
> 注意到只支持.properties的读取，请问是否支持yaml格式的读取呢？

支持 yaml 和 yml，通过以下方式格式化。
https://github.com/apolloconfig/agollo/blob/559999e53619fc5e6371345a553970bb0aa16f0a/client.go#L55

**Comment by leoyox** [comment]
> extension.AddFormatParser(constant.YAML, &yaml.Parser{})

似乎没什么用
