### ISSUE TITLE
[BUG] GetBoolValue error

### ISSUE THREAD

**Issue by leoyox** [apolloconfig/agollo#242]
**请简单描述bug的场景**
properties中配置了bool、int值，客户端调用GetBoolValue、GetIntValue来取，结果总是得到默认值

**期望**
期望GetBoolValue返回对应的bool值

**截图**
如有

**Agollo 版本 :**
 - Version 4

**Comment by JhouXerox** [comment]
我也碰到了这个问题.
原因是在 repository.go 中 GetIntValue 里 getConfigValue返回的interface{}是string类型的.没法直接通过.(int)转换回来.
要尝试parseInt之类的方法
