### ISSUE TITLE
[BUG]执行用例出错undefined: DefaultLogger

### ISSUE THREAD

**Issue by gocpplua** [apolloconfig/agollo#248]
**请简单描述bug的场景**
ubuntu 16.04
go version go1.17.5 linux/amd64

1. go mod init apollo
2. touch apollo.go
3. 使用实例代码
```
package main

import (
	"fmt"

	"github.com/apolloconfig/agollo/v4"
	"github.com/apolloconfig/agollo/v4/env/config"
)

func main() {
	c := &config.AppConfig{
		AppID:          "testApplication_yang",
		Cluster:        "dev",
		IP:             "http://106.54.227.205:8080",
		NamespaceName:  "dubbo",
		IsBackupConfig: true,
		Secret:         "6ce3ff7e96a24335a9634fe9abca6d51",
	}

	agollo.SetLogger(&DefaultLogger{})

	client, _ := agollo.StartWithConfig(func() (*config.AppConfig, error) {
		return c, nil
	})
	fmt.Println("初始化Apollo配置成功")

	//Use your apollo key to test
	cache := client.GetConfigCache(c.NamespaceName)
	value, _ := cache.Get("key")
	fmt.Println(value)
}
```
4. 执行 go mod dity
5. go run apollo.go

错误：
$ go run apollo.go 
# command-line-arguments
./apollo.go:20:20: undefined: DefaultLogger

**Agollo 版本 :**
- github.com/apolloconfig/agollo/v4 v4.2.0

**Comment by zouyx** [comment]
主页的 demo 是有点问题，可以参考以下 demo 项目

https://github.com/zouyx/agollo_demo/blob/master/helloworld/check.go

**Comment by zjutjsj1004** [comment]
> 主页的 demo 是有点问题，可以参考以下 demo 项目
> 
> https://github.com/zouyx/agollo_demo/blob/master/helloworld/check.go

谢谢. zouyx你主页的demo不替换下吗?
