### ISSUE TITLE
apollo同步配置或者修改配置时触发onChange会panic

### ISSUE THREAD

**Issue by leecode398** [apolloconfig/agollo#251]
#### issue
apollo同步配置或者修改配置时触发onChange时会panic

![](https://raw.githubusercontent.com/leecode398/images/master/picgo/20220927205622.png)

初步定位问题是因为获取缓存时没有对返回值判空：
![](https://raw.githubusercontent.com/leecode398/images/master/picgo/20220927205728.png)

#### version
	github.com/apolloconfig/agollo/v4 v4.2.0 // indirect

**Comment by zouyx** [comment]
我见close 了 issue，是否能给我说下为什么？确实是个问题？还是不是？
