### ISSUE TITLE
Update apollo demo server address

### ISSUE THREAD

**Issue by nobodyiam** [apolloconfig/agollo#257]
The original apollo demo server(`106.54.227.205`) is about to be expired, we need to update the server address to `81.68.181.139` and also the secret/token if necessary, see https://github.com/apolloconfig/apollo/pull/4628

**Comment by zouyx** [comment]
> The original apollo demo server(`106.54.227.205`) is about to be expired, we need to update the server address to `81.68.181.139` and also the secret/token if necessary, see [apolloconfig/apollo#4628](https://github.com/apolloconfig/apollo/pull/4628)

ok
