### ISSUE TITLE
支持动态添加新的namespace吗

### ISSUE THREAD

**Issue by qshuai** [apolloconfig/agollo#259]
我想实现运行时动态添加namespace，然后可以在cache中查询到新添加namespace的配置数据，现在的api可以做到么？

**Comment by qshuai** [comment]
我自己二开实现了该特性，需要的朋友可以移步：https://github.com/qshuai/agollo#%E5%8A%A8%E6%80%81namespace%E7%89%B9%E6%80%A7

**Comment by zouyx** [comment]
> 我自己二开实现了该特性，需要的朋友可以移步：https://github.com/qshuai/agollo#%E5%8A%A8%E6%80%81namespace%E7%89%B9%E6%80%A7

如果有可能，可以提交 pr

**Comment by fengqi** [comment]
你的实现方式是这样吗：
定时拉取全部namespace，然后配置正则匹配想要的部分

调整成这样是不是比较好：
在application这里配置要启用的namespace，如：namespace=mysql,redis,kafka，当修改的时候这个值是会自动同步到client的，client根据这个值去获取配置就好了，不用定时任务，也不用正则

按照目前的代码结构，只需要有个内置的change监听，设置调用下SetCurrentApolloConfig就可以了

**Comment by qshuai** [comment]
> 你的实现方式是这样吗： 定时拉取全部namespace，然后配置正则匹配想要的部分
> 
> 调整成这样是不是比较好： 在application这里配置要启用的namespace，如：namespace=mysql,redis,kafka，当修改的时候这个值是会自动同步到client的，client根据这个值去获取配置就好了，不用定时任务，也不用正则
> 
> 按照目前的代码结构，只需要有个内置的change监听，设置调用下SetCurrentApolloConfig就可以了

嗯呢，不错的想法！

**Comment by fengqi** [comment]
不过我好奇应用场景是什么，按说新增配置不应该都是需要提前适配代码的吗，这就需要重新部署或者重新启动的。

**Comment by qshuai** [comment]
> 不过我好奇应用场景是什么，按说新增配置不应该都是需要提前适配代码的吗，这就需要重新部署或者重新启动的。

一个可能但不一定合理的场景：一个类目相关的服务，提供类目相关配置的查询能力，而类目是可以横向扩展的；也就是说在服务启动的时候，并不知道有多少个类目需要配置。为了实现无需重启服务就能提供这样能力的诉求，就衍生了这么一个功能。

一开始我并不同意业务方的诉求，其实这个诉求可以通过如下方式满足：搭建一个类目的后台管理，再加上一个持久化存储，程序实时查询数据库的数据即可。但是业务方看中了apollo配置中心已经存在的灰度发布、审核流程、变更历史查询等能力，不想重复建设，把配置中心当做数据库在使用了。所以~

**Comment by fengqi** [comment]
确实不太合理，当成数据库用了
