### ISSUE TITLE
[求助]当我使用GetSliceValue()不可用

### ISSUE THREAD

**Issue by SonderEASE** [apolloconfig/agollo#264]
<img width="676" alt="image" src="https://user-images.githubusercontent.com/37165936/205014040-a2f96c05-f2e6-488c-aa00-eefc20d06d77.png">
配置如上，调用后GetSliceValue() 后，触发： convert to []string fail ! source type:[]interface {}

properties的value该如何配置才能让这里的value识别为[]string?

**Comment by zouyx** [comment]
> <img alt="image" width="676" src="https://user-images.githubusercontent.com/37165936/205014040-a2f96c05-f2e6-488c-aa00-eefc20d06d77.png">
> 
> 配置如上，调用后GetSliceValue() 后，触发： convert to []string fail ! source type:[]interface {}
> properties的value该如何配置才能让这里的value识别为[]string?

可能要改下程序，我这两天检查下。

**Comment by SonderEASE** [comment]
谢谢～ 目前我是自己加了一个string => []string的转换

**Comment by zouyx** [comment]
> 谢谢～ 目前我是自己加了一个string => []string的转换

我觉得这是可以的
