### ISSUE TITLE
[BUG] 关于常见问题 issues 访问不到

### ISSUE THREAD

**Issue by ChoGathK** [apolloconfig/agollo#267]
应该是仓库地址转交导致的，可以访问的地址是：[周期性的连接Apollo服务器端超时失败](https://github.com/apolloconfig/agollo/issues/10)

**Comment by zouyx** [comment]
感谢提醒，应该是因为迁移过仓库导致的。我修正下。

**Comment by zouyx** [comment]
已修复，谢谢
