### ISSUE TITLE
[BUG]无法获取最新配置

### ISSUE THREAD

**Issue by blackehao** [apolloconfig/agollo#278]
**请简单描述bug的场景**
修改配置后无法获取最新配置，只有重启服务端后内短暂的几分钟内修改配置运行脚本可以获取最新配置
仅使用提供的"启动 agollo"运行，未做其他任何代码封装
1. apollo部署方式:  helm
2. apollo部署版本：2.1.0
3. go sdk 版本：4.3.0

**Comment by AllenWrong** [comment]
解决了没，我也遇到了这个问题，是哪里的问题啊
