### ISSUE TITLE
判断是不是存在问题，我们是想要把这个映射保存在本地缓存中，但是判断的键和存储的键不一样，永远不可能用到缓存中数据

### ISSUE THREAD

**Issue by tiandi0716** [apolloconfig/agollo#285]
https://github.com/apolloconfig/agollo/blob/master/env/file/json/json.go
![image](https://github.com/apolloconfig/agollo/assets/41275334/9d03b50f-6c9d-442e-8f9e-7721043b82e4)

**Comment by nobodyiam** [comment]
Looks like a bug to me.
